config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :images, only: [:create, :show, :update, :destroy]
    resources :categorys, only: [:create, :show, :update, :destroy]
    resources :brands, only: [:create, :show, :update, :destroy]
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'purchase/:id'=> 'products#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'products#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'products#done', as: 'done'                      #購入完了ページ
    end
  end
  resources :destinations, only: [:index, :edit, :update]
  root 'products#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[twitter]
  
  mount_uploader :user_image, ImageUploader       
         
    def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      end
    end

  validates :nickname , :family_name, :first_name, :family_name_kana, :first_name_kana, presence: true

  has_one :card
  has_one :destination
  has_many :products
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @user = User.new
  end

  def create
    params[:user][:birth_day]
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @destination = @user.build_destination
    render :new_destination
  end

  def create_destination
    @user = User.new(session["devise.regist_data"]["user"])
    @destination = Destination.new(destination_params)
    unless @destination.valid?
      flash.now[:alert] = @destination.errors.full_messages
      render :new_destination and return
    end
    @user.build_destination(@destination.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  protected

  def destination_params
    params.require(:destination).permit(:post_code, :address, :prefecture, :city, :building_name, :family_name, :first_name, :family_name_kana, :first_name_kana, :phone_number)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @products = current_user.products
  end
  
  def show
    @products = current_user.products
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_image, :nickname, :introduction)
  end

end

app/views/users/edit.html.haml
= render partial: 'shared/main_header'

.form
  = form_with(model: @user, local: true) do |f|
    .profile-container
      .profile-head プロフィール 編集
      .profile-top 
        .image-form
          = f.label :user_image, class: "user-image" do
            = image_tag current_user.user_image.url
            = f.file_field :user_image, class: 'hidden'
        .nickname-box
          .current-nickname
            = current_user.nickname
          = f.text_field :nickname, class: 'nickname-form', placeholder: '新しいニックネーム'
      .profile-setting
        .text-form
          = f.text_area :introduction, class: "introduction_edit", rows: "7", maxlength: "1000", placeholder: "自己紹介（1,000文字以内）\n\n例）\nはじめまして！\n\n未使用品を中心に出品をさせていただきます。\n非喫煙者で、ペットは飼っておりません。\n即購入は大歓迎です！\n\nよろしくお願いします。"
        .btn-form
          = f.submit "変更する", class:"edit-btn", data: { confirm: "この内容で登録しますか？"}

= render partial: 'shared/main_footer'

app/views/users/index.html.haml
= render partial: 'shared/main_header'

.user_intro
  .profile-container
    .profile-head プロフィール
    .profile-icon
      .photo-box
        .user_image
          = image_tag current_user.user_image.url
      .profile_right    
        .nickname
          = current_user.nickname
        %ul.sell_info
          %li.title 出品数
          %li.count 25
    .profile-setting
      .profile-setting__text-box
        .introduction
          = current_user.introduction
    .sell-tab 出品リスト
    .tab-area
      - @products.each do |product|
        %ul.list-show
          = link_to product_path(product) do
            %li.item
              .image-box
                .img
                  = image_tag product.images.first.src.url
              .name
                = product.name
              .updated
                = product.updated_at.strftime("%Y-%m-%d %H:%M") 

= render partial: 'shared/main_footer'        

app/views/users/show.html.haml
= render partial: 'shared/main_header'

.MypageDisplay  
  .MypageContainer
    .side-var
      .mypage-nav
        %ul.mypage-nav__list
        = link_to user_path do
          %li.mypage-nav__list__item-top マイページ
          = link_to new_product_path do   
            %li.mypage-nav__list__item
              .item-name 出品する
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 出品した商品-出品中
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 出品した商品-取引中
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 出品した商品-売却済み
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 購入した商品-取引中
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 購入した商品-過去の取引
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 購入した商品-売却済み
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 評価一覧
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name お問い合わせ
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x                                                                  

        %h3.mypage-nav__head FURIペイ
        %ul.mypage-nave__list
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 売上・振込申請
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x 
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name ポイント
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x       
               
        %h3.mypage-nav__head 設定
        %ul.mypage-nave__list
          = link_to edit_user_path(current_user) do
            %li.mypage-nav__list__item
              .item-name プロフィール
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 発送元・お届け先住所変更
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x 
          = link_to new_card_path do   
            %li.mypage-nav__list__item
              .item-name 支払い方法
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name メール/パスワード
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 本人情報
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x 
          = link_to user_path do   
            %li.mypage-nav__list__item
              .item-name 電話番号の確認
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x 
          = link_to destroy_user_session_path, method: :delete do   
            %li.mypage-nav__list__item
              .item-name ログアウト
              .icon-arrow-right
                .fa.fa-caret-right.fa-2x        
                
    .main-content
      .user-icon-box
        = link_to edit_user_path(current_user) do
          .user-icon
            = image_tag current_user.user_image.url
        .trade-info
          .trade-info__nickname
            = current_user.nickname
          .trade-info__count  
            .trade-info__count__sell-title 出品数
            .trade-info__count__sell-count 25      
            .trade-info__count__buy-title 購入数
            .trade-info__count__buy-count 17

      %ul.trade-tab
        %li.active 出品リスト
        %li 購入リスト
  
      .tab-area
        - @products.each do |product|
          %ul.list-show
            = link_to product_path(product) do
              %li.item
                .image-box
                  .img
                    = image_tag product.images.first.src.url
                .name
                  = product.name
                .updated
                  = product.updated_at.strftime("%Y-%m-%d %H:%M")  
          %ul
            = link_to user_path do
              %li.item
                .image-box
                  .img
                    = image_tag product.images.first.src.url
                .name キーケース
                .updated
                  = product.updated_at.strftime("%Y-%m-%d %H:%M")   
            = link_to user_path do
              %li.item
                .image-box
                  .img
                    = image_tag product.images.first.src.url
                .name 手帳
                .updated
                  = product.updated_at.strftime("%Y-%m-%d %H:%M")  
            = link_to user_path do
              %li.item
                .image-box
                  .img
                    = image_tag product.images.first.src.url
                .name ハンカチ
                .updated
                  = product.updated_at.strftime("%Y-%m-%d %H:%M")  
            = link_to user_path do
              %li.item
                .image-box
                  .img
                    = image_tag product.images.first.src.url
                .name ブレスレット
                .updated
                  = product.updated_at.strftime("%Y-%m-%d %H:%M") 

= render partial: 'shared/main_footer'                   