config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :images, only: [:create, :show, :update, :destroy]
    resources :categorys, only: [:create, :show, :update, :destroy]
    resources :brands, only: [:create, :show, :update, :destroy]
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'purchase/:id'=> 'products#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'products#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'products#done', as: 'done'                      #購入完了ページ
    end
  end
  resources :destinations, only: [:index, :edit, :update]
  root 'products#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end


end

app/views/shared/_main_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul.content__list
        %li
          = link_to root_path do
            会社概要（運営会社）
        %li
          = link_to root_path do
            プライバシーポリシー
        %li
          = link_to root_path do
            FURIMA利用規約
        %li
          = link_to root_path do
            ポイントに関する特約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul.content__list
        %li
          = link_to root_path do
            カテゴリー一覧
        %li
          = link_to root_path do
            ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ&ガイド
      %ul.content__list
        %li
          = link_to root_path do
            FURIMAガイド
        %li
          = link_to root_path do
            FURIMAロゴ利用ガイドライン
  .footer__logo
    = link_to root_path do
      = image_tag asset_path("logo/logo-white.png")
  %p
    &copy; FURIMA
  = link_to new_product_path do   
    .sell-btn
      %span.sell-btn__text
        出品する
      = image_tag asset_path("icon/icon_camera.png")

app/views/shared/_main_header.html.haml
.Header
  .HeaderInner
    .HeaderMain
      .HeaderMain__logo
        = link_to root_path do
          = image_tag asset_path("logo/logo.png")
          
      .HeaderMain__search-box          
        = form_tag(search_products_path, method: 'get') do      
          = text_field_tag :keyword, '', placeholder: "キーワードから探す", class: "search-input" 
          = submit_tag '検索', class: "search-btn" , name: nil           
          = link_to(search_products_path, method: 'get') do
            .search-icon
              = image_tag asset_path("icon/icon-search 1.png")
          .search-btn_back    
    .HeaderNav
      %ul.HeaderNav__lists--left
        %li.list--left
          = link_to root_path do
            カテゴリー
        %li.list--right
          = link_to root_path do
            ブランド
      - if user_signed_in?
        %ul.HeaderNav__lists--right
          %li.list--left
            = link_to user_path(current_user) do
              マイページ
          %li.list--right
            = link_to destroy_user_session_path, method: :delete do
              ログアウト
      - else
        %ul.HeaderNav__lists--right
          %li.list--left
            = link_to new_user_session_path do
              ログイン
          %li.list--right
            = link_to new_user_registration_path do
              新規会員登録  

app/views/shared/_sub_footer.html.haml
.sub-footer
  .contents
    %ul.contents-list
      %li.content
        = link_to "#", class: "private-policy" do
          プライバシーポリシー
      %li.content
        = link_to "#", class: "user-policy" do
          フリマ利用規約
      %li.content
        = link_to "#", class: "point-policy" do
          ポイントに関する特約
  = link_to root_path, class: "logo" do
    = image_tag(asset_path("logo/logo.png"), class:"logo-image")
  .company-name ©︎ FURIMA

  

app/views/shared/_sub_header.html.haml
.sub-header
  = link_to root_path do
    = image_tag(asset_path("logo/logo.png"), class:"logo")