config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :images, only: [:create, :show, :update, :destroy]
    resources :categorys, only: [:create, :show, :update, :destroy]
    resources :brands, only: [:create, :show, :update, :destroy]
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'purchase/:id'=> 'products#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'products#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'products#done', as: 'done'                      #購入完了ページ
    end
  end
  resources :destinations, only: [:index, :edit, :update]
  root 'products#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end


end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:delete, :show]

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to cards_path
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def buy #クレジット購入
    if @card.blank?
      redirect_to action: "new"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
      @product = Product.find(params[:product_id])
     # 購入した際の情報を元に引っ張ってくる
      @card = current_user.credit_card
     # テーブル紐付けてるのでログインユーザーのクレジットカードを引っ張ってくる
     Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
     # キーをセットする(環境変数においても良い)
      Payjp::Charge.create(
      amount: @product.price, #支払金額
      customer: @card.customer_id, #顧客ID
      currency: 'jpy', #日本円
      )
     # ↑商品の金額をamountへ、cardの顧客idをcustomerへ、currencyをjpyへ入れる
      if @product.update(status: 1, buyer_id: current_user.id)
        flash[:notice] = '購入しました。'
        redirect_to controller: "products", action: 'show'
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: "products", action: 'show'
      end
     #↑この辺はこちら側のテーブル設計どうりに色々しています
    end
  end

  private
  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
= form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm", class: "cards-form") do
  = render partial: 'shared/sub_header'
  .cards_header
    %h2.cards_title
      カード情報入力
    .cards_contents
      %label カード番号
      %br
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %ul.cards-logo
        %li
          = image_tag asset_path("cards/visa.svg")
        %li
          = image_tag asset_path("cards/mc_vrt_pos.svg")
        %li
          = image_tag asset_path("cards/jcb.svg")
        %li
          = image_tag asset_path("cards/saison-card.svg")
        %li
          = image_tag asset_path("cards/amex.svg")
        %li
          = image_tag asset_path("cards/discover.svg")
      %br
      %label 有効期限
      %br
      %select#exp_month{name: "exp_month", type: "text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %span 月/
      %select#exp_year{name: "exp_year", type: "text"}
        %option{value: ""} --
        %option{value: "2019"}19
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      %span 年
      %br
      %br
      %label セキュリティコード
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      %br
      = submit_tag "追加する", id: "token_submit", class: "submit"

  = render partial: 'shared/sub_footer'      

app/views/cards/show.html.haml
= render partial: 'shared/sub_header'

.cards-show
  .cards-show__title
    %h2 登録クレジットカード情報
    %br
    .cards-contents
      %p
        = "**** **** **** " + @default_card_information.last4
      %br
      %p
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する

= render partial: 'shared/sub_footer'