config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :images, only: [:create, :show, :update, :destroy]
    resources :categorys, only: [:create, :show, :update, :destroy]
    resources :brands, only: [:create, :show, :update, :destroy]
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'purchase/:id'=> 'products#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'products#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'products#done', as: 'done'                      #購入完了ページ
    end
  end
  resources :destinations, only: [:index, :edit, :update]
  root 'products#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end


end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  belongs_to_active_hash :brand
  belongs_to_active_hash :size
  belongs_to_active_hash :status
  belongs_to_active_hash :shippingcost
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shippingdays
  belongs_to_active_hash :shipping

  scope :search, -> (search){ where('name LIKE(?)', "%#{search}%")}
  
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, length: { maximum: 40 }, presence: true
  validates :description, length: { maximum: 1000 }, presence: true
  validates :price, numericality: { :greater_than_or_equal_to => 500, :less_than_or_equal_to => 9999999 }, presence: true
  validates :status_id, :size_id, :shippingcost_id, :shippingdays_id, :prefecture_id, :category_id, :shipping_id, :images, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, except: [:index, :new, :create, :show, :get_category_children, :get_category_grandchildren, :search]
  before_action :set_card, only: [:purchase, :pay, :done]


  def index
    @products = Product.includes(:images).order('created_at DESC').limit(3)
    @products2 = Product.includes(:images).order('created_at ASC').limit(3)
  end

  def new
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
    @product = Product.new
    @product.images.new
    @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択して下さい")
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

 # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      render :create
    else
      @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("選択して下さい")
      render :new
    end
  end

  def edit
    grandchild_category = @product.category
    child_category = grandchild_category.parent

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      redirect_to edit_product_path(params[:id]), flash: { alert: "編集に失敗しました"}
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      redirect_to product_path(@product.id)
    end
  end

  def search
    @products = Product.search(params[:keyword])
  end

  def purchase
    if @card.blank?
      flash.now[:alert] = 'カードを登録してください。'
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    charge = Payjp::Charge.create(
    amount: @product.price,
    customer: @card.customer_id,
    card: params['payjp-token'],
    currency: 'jpy'
    )
    if @product.update( buyer_id: current_user.id)
      redirect_to done_products_path(@product.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def done
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    #保管した顧客IDでpayjpから情報取得
    customer = Payjp::Customer.retrieve(@card.customer_id)
    #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    @default_card_information = customer.cards.retrieve(@card.card_id)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :status_id, :size_id, :shippingcost_id, :shippingdays_id, :prefecture_id, :category_id, :brand_id, :shipping_id, :buyer_id, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_sub_footer.html.haml
.sub-footer
  .contents
    %ul.contents-list
      %li.content
        = link_to "#", class: "private-policy" do
          プライバシーポリシー
      %li.content
        = link_to "#", class: "user-policy" do
          フリマ利用規約
      %li.content
        = link_to "#", class: "point-policy" do
          ポイントに関する特約
  = link_to "#", class: "logo" do
    = image_tag(asset_path("logo/logo.png"), class:"logo-image")
  .company-name ©︎ FURIMA

app/views/products/create.html.haml
-# 商品出品完了画面
.sale-done
  = render partial: 'shared/sub_header'
  .sale-done__header
    %h2.done-title
      出品が完了しました！
    .done-message
      %p あなたが出品した商品は
      = link_to "「出品した商品一覧」", user_path(current_user), class:"btn"
      %p からいつでも見ることが出来ます。
    .done-contents
      .continue-sale
        = link_to "続けて出品する",new_product_path, class:"btn"
      .return-top
        =link_to 'TOPページへ戻る',root_path, class:"return_btn"
  = render partial: 'shared/sub_footer'

app/views/products/done.html.haml
= render partial: 'shared/sub_header'

-# 商品購入完了画面
.purchase-verification
  .purchase-verification__header
    %h2.purchase-title
      購入完了
    .done-message
      %p 発送をお待ちください
      %p 出品者からの発送通知をお待ち下さい
    .top-images
      %ul
        %li
          - @product.images.first(1).each do |image|
            = image_tag image.src.url, class: 'top-image'
          %ul
            - @product.images[1..3].each do |image|
              %li
                = image_tag image.src.url, class: 'sub-image' 
    .contents-title
      %h2.title
        商品名
      %h2.detail
        = @product.name
    .contents-title
      %h2.title
        送料込み
      %h2.detail
        = "¥#{@product.price}"
    .buyer-contents
      %h2.delivary-title
        配送先
      .address-delivary
        %h2.title
          住所
        %h2="〒 #{@product.user.destination.post_code} #{current_user.destination.prefecture} #{current_user.destination.city} #{current_user.destination.address} #{current_user.destination.building_name}"
      .name-delivary
        %h2.title
          名前
        %h2="#{current_user.family_name} #{current_user.first_name} " 
      .method-number
        %h2.title
          支払方法
          %h2
            = "**** **** **** " + @default_card_information.last4
          %h2
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
      .return-top
        =link_to 'TOPページへ戻る',root_path, class:"return_btn"

= render partial: 'shared/sub_footer'

app/views/products/index.html.haml
= render partial: 'shared/main_header'

.top-view
  %section.top-view__top-img
    .contents
      %h2.contents__subtitle 
        %br
        人生を変えるフリマアプリ
      %p.contents__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .contents__btn
        = link_to image_tag(asset_path("icon/appstore.svg"), class:"a-btn"), root_path
        = link_to image_tag(asset_path("icon/google-play.svg"), class:"g-btn"), root_path

  %section.top-view__reason
    %h2.title
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag asset_path("pict/pict-reason-01.jpg")
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag asset_path("pict/pict-reason-02.jpg")
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .list__pict
          %span.number 3
          = image_tag asset_path("pict/pict-reason-03.jpg")
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&購入！

  %section.top-view__mid-img
    .contents
      .contents__inner
        %h2.subtitle
          会員数日本一位
        %p.text
          FURIMAは、フリマアプリで最も人気。
          %br
          出品・購入回数も業界最多です！
          %br
          欲しかったあの商品に出会えるかもしれません。
        .btn
          = link_to image_tag(asset_path("icon/appstore.svg"), class:"a-btn"), root_path
          = link_to image_tag(asset_path("icon/google-play.svg"), class:"g-btn"), root_path

  %section.top-view__feature
    %h2.head
      FURIMAの特徴
    .lists
      %section.list
        %figure.list__img
          = image_tag asset_path("icon/icon-01.png")
        %h3.list__title
          簡単に売り買いできる
        %p.list__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.list
        %figure.list__img
          = image_tag asset_path("icon/icon-02.png")
        %h3.list__title
          売上金は即日振込に対応
        %p.list__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      %section.list
        %figure.list__img
          = image_tag asset_path("icon/icon-03.png")
        %h3.list__title
          様々な支払いに対応
        %p.list__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.top-view__pickup
    %h2.head
      ピックアップカテゴリー
    .products
      .products__head
        = link_to "/" do
          %h3.title
            新規投稿商品
      .products__lists
        - @products.each do |product|
          .list
            = link_to product_path(product.id) do
              %figure.list-img
                -if product.buyer_id.present? 
                  %p.sold-out
                    SOLD OUT
                = image_tag product.images.first.src.url
              .list-body
                %h3.name
                  = product.name
                  .details
                    %ul
                      %li
                        = product.price
                        円
                      %li
                        %i.fa.fa-star.likeicon
                        0
                    %p
                      (税込)
          

  %section.top-view__pickup
    %h2.head
      ピックアップブランド
    .products
      .products__head
        = link_to "/" do
          %h3.title
            アーカイブ
      .products__lists
        - @products2.each do |product|
          .list
            = link_to product_path(product.id) do
              %figure.list-img
                -if product.buyer_id.present? 
                  %p.sold-out
                    SOLD OUT
                = image_tag product.images.first.src.url
              .list-body
                %h3.name
                  = product.name
                  .details
                    %ul
                      %li
                        = product.price
                        円
                      %li
                        %i.fa.fa-star.likeicon
                        0
                    %p
                      (税込)

%aside.bottom-img
  .contents
    %h2.contents__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.contents__text
      今すぐ無料ダウンロード！
    .contents__icon
      = link_to image_tag(asset_path("icon/appstore.svg"), class:"a-btn"), root_path
      = link_to image_tag(asset_path("icon/google-play.svg"), class:"g-btn"), root_path

= render partial: 'shared/main_footer'      

app/views/products/purchase.html.haml
= render partial: 'shared/sub_header'

.purchase-verification
  .purchase-verification__header
    %h2.purchase-title
      購入内容の確認
    .top-images
      %ul
        %li
          - @product.images.first(1).each do |image|
            = image_tag image.src.url, class: 'top-image'
          %ul
            - @product.images[1..3].each do |image|
              %li
                = image_tag image.src.url, class: 'sub-image' 
    .contents-title
      %h2.title
        商品名
      %h2.detail
        = @product.name
    .contents-title
      %h2.title
        送料込み
      %h2.detail
        = "¥#{@product.price}"
    .contents-title
      %h2.title
        支払金額
      %h2.contents
        =" ¥#{@product.price}"
    .contents-btn
      - if @default_card_information.blank?
        = link_to new_card_path(current_user.id) do
          %h2.title
            支払方法を選択してください
      - else
        = form_tag(action: :pay, method: :post) do
          %button.buy-btn 購入する
    .buyer-contents
      %h2.delivary-title
        配送先
      .address-delivary
        %h2.title
          住所
        %h2="〒 #{@product.user.destination.post_code} #{current_user.destination.prefecture} #{current_user.destination.city} #{current_user.destination.address} #{current_user.destination.building_name}"
      .name-delivary
        %h2.title
          名前
        %h2="#{current_user.family_name} #{current_user.first_name} " 
      .method-number
        %h2.title
          支払方法
        - if @default_card_information.blank?
          %h2.method-change
            クレジットカードが登録されていません
        - else
          %h2
            = "**** **** **** " + @default_card_information.last4
          %h2
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = link_to new_card_path(current_user.id), class:"cards-change" do
              変更する

  = render partial: 'shared/sub_footer'

app/views/products/search.html.haml
= render partial: 'shared/main_header'

.SearchView
  %section.SearchView__result
    %h2.head 検索結果
    %h3.word
      = "' #{params[:keyword]} '"
    .products
      .products__lists
        - @products.each do |product|
          .list
            = link_to product_path(product) do
              %figure.list-img
                -if product.buyer_id.present? 
                  %p.sold-out SOLD OUT
                = image_tag product.images.first.src.url
              .list-body
                %h3.name
                  = product.name
                  .details
                    %ul
                      %li
                        = product.price
                        円
                      %li
                        %i.fa.fa-star.likeicon
                        0
                    %p (税込)

= render partial: 'shared/main_footer'

app/views/products/show.html.haml
= render partial: 'shared/main_header'

.main-product
  .product-detail
    .product-detail__main
      .product-detail__main__content
        .detail-box
          .product-name
            = @product.name
          .product-image
            %ul
              %li
                - @product.images.first(1).each do |image|
                  = image_tag image.src.url, class: 'top-image'
                %ul
                  - @product.images[1..3].each do |image|
                    %li
                      = image_tag image.src.url, class: 'sub-image' 
          .product-price
            %span
              ￥
              = @product.price
            .product-price__cost
              %span (税別)
              %span 送料込
          .product-introduction
            = @product.description
          .product-table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = link_to @product.user.nickname, users_path(@product.user.id)
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#" do
                      = @product.category.parent.parent.name
                      %br
                    = link_to "#" do
                      = @product.category.parent.name
                      %br
                    = link_to "#" do
                      = @product.category.name
                %tr
                  %th ブランド
                  %td
                    = @product.brand.name
                %tr
                  %th 商品のサイズ
                  %td
                    = @product.size.name
                %tr
                  %th 商品の状態
                  %td
                    = @product.status.name
                %tr
                  %th 配送料の負担
                  %td
                    = @product.shippingcost.name
                %tr
                  %th 発送元の地域
                  %td
                    = link_to "#" do
                      = @product.prefecture.name
                %tr
                  %th 発送日の目安
                  %td
                    = @product.shippingdays.name
          .optional-area
            %ul
              %li#like-btn.optional-btn.like-btn
                %i.fa.fa-star
                お気に入り 0
            %ul.optional
              %li.optinal-btn
                = link_to "#" do
                  不適切な商品の通報
          .edit-menu
            - if user_signed_in? && current_user.id == @product.user_id
              .more
                .more_list
                  = link_to "/products/#{@product.id}/edit", method: :get ,class:"edit-btn" do
                    %p.text
                      編集
                  = link_to "/products/#{@product.id}", method: :delete, class:"delet-btn" do
                    %p.text
                      削除
            - elsif user_signed_in? && current_user.id != @product.user_id && @product.buyer_id.blank?
              .parcase-product
                = link_to purchase_products_path, class:"purchase-btn" do
                  .purchase-btn__text
                    購入する
            - elsif user_signed_in? && current_user.id == @product.buyer_id
            - elsif user_signed_in? && current_user.id != @product.buyer_id
            - else
              .parcase-product
                = link_to new_user_registration_path, class:"purchase-btn" do
                  .purchase-btn__text
                    会員登録はこちら
                  
        .comment-box
          %ul.comment-contents
          %form.new-comment-form
            %textarea#comment-body
            %p.notice-message
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            %button.comment-btn
              %li.fa.fa-comment
              コメントする
      %ul.links
        %li
          = link_to "#" do
            %span
            < 前の商品
        %li
          = link_to "#" do
            %span
            後ろの商品 >
      .relate-item
        = link_to root_path do
          商品一覧に戻る

= render partial: 'shared/main_footer'          